# Set title for project documentation
site_name: Knowledge Sharing

# Set the name of author. This will add a meta data tag to the generated HTML header
site_author: Kai.Zhou
repo_url: https://github.com/zhoukaisspu/ks_blog
copyright: 'Copyright &copy; 2019 - 2020 Kai.Zhou'
theme:
  language: 'zh'
  name: 'material'
  features:
    - navigation.tabs
  icon:
    logo: 'material/cloud'
markdown_extensions:
  - admonition
  - codehilite
nav:
  - 'Home': 
    - 'Home': index.md
    - '网站部署': shell/CI/deployGithubIO.md
    - '学习资源': trainingResource.md
  - 'C++':
    - 'C++学习资源': C++/cppTraining.md
    - '核心特性':
      - '构造函数': C++/coreFeature/specialMemberFunction/constructor.md
      - '委托构造': C++/coreFeature/specialMemberFunction/delegating_constructor.md
      - '操作符重载':
        - '操作符重载_part.I': C++/coreFeature/specialMemberFunction/operatorOverload.md
        - '操作符重载_part.II': C++/coreFeature/specialMemberFunction/operatorOverload2.md
        - '操作符重载_part.III': C++/coreFeature/specialMemberFunction/operatorOverload3.md
      - '右值引用': C++/coreFeature/specialMemberFunction/rvalueReference.md
    - 'C++对象模型':
      - '局部静态对象': C++/objectModel/scoped_static.md
    - 'C++标准库':
      - 'std::thread': C++/standardLibrary/multiThread/thread.md
      - 'std::thread::native_handle': C++/standardLibrary/multiThread/thread_nativeHandle.md
    - 'C++技术总结':
      - '单例模式': C++/others/singleTon_mutex_call_once.md
      - '单例模式_2': C++/others/singleTon_atomic_static_member.md
  - 'javaScript':
    - '对象设计': JS/ObjectOriented.md
  - 'python':
    - '进入python世界': python/home.md
    - 'cpython解释器': python/cpython.md
    - 'pip': python/pip.md
    - '下划线的意义': python/unserscore.md
    - '定义函数': python/function_py.md
    - '函数参数': python/functionParameter_py.md
    - '全局变量的使用': python/globalVariable.md
    - '类之封装/继承': python/class_py.md
    - '类之多态/重载': python/class2_py.md
    - '定制类': python/customizationClass_py.md
    - '类属性/实例属性': python/property_py.md
    - '可调用对象': python/callable_py.md
    - '模块和包': python/module.md
    - 'SQLite': python/sqlite.md
    - '文件操作': python/files.md
    - '标准库':
      - '获取版本号': python/codeSnippet/py_ver.md
      - 'argparse': python/codeSnippet/argparse.md
      - 'subprocess': python/subprocess.md
      - 'sys': python/library/sys.md
      - 'os': python/library/os.md
  - 'swift':
    - 'Home: xcode的继续集成': swift/build.md
    - '1.1: 数据类型及变量': swift/basic.md
    - '1.2: 函数定义': swift/function.md
    - '2.1: 类基本': swift/class_basic.md
    - '2.2: 类属性': swift/class_property.md
    - '2.3: 类方法': swift/class_method.md
    - '2.4: 类subscript': swift/class_subscript.md
    - '2.5: 类型转换': swift/type_casting.md
  - 'linux':
    - 'linux':
      - 'Linux指令': shell/linux/command.md
      - '用户管理': shell/linux/user.md
      - 'sudo vs su': shell/linux/sudo.su.md
      - 'Linux工具': shell/linux/tools.md
      - 'ext2文件系统': shell/linux/filesystem.md
      - '硬/符号链接': shell/linux/hard_softlink.md
      - 'FHS': shell/linux/fhs.md
      - 'C编译流程': shell/linux/c_compilation.md
    - 'shell Script':
      - 'shell script简介': shell/shellScript/home.md
      - '变量': shell/shellScript/variable.md
      - '条件判断': shell/shellScript/test.md
      - 'shell替换': shell/shellScript/substitution.md
      - '字符串操作': shell/shellScript/stringManipulation.md
      - '文件测试': shell/shellScript/file_operator.md
      - '函数定义': shell/shellScript/shell_function.md
      - '数组': shell/shellScript/shellscript_array.md
      - '重定向': shell/shellScript/redirection.md
      - '调试': shell/shellScript/debug.md
      - '常用代码片段': shell/shellScript/shCodeSnippet.md
    - 'git':
      - 'clone': shell/linux/tools/git/clone.md
      - 'branch': shell/linux/tools/git/branch.md
      - 'config': shell/linux/tools/git/config.md
      - 'tag': shell/linux/tools/git/tag.md
      - 'gitHubTips': shell/linux/tools/git/githubTips.md
  - '逆向工程':
    - '基础篇':
      - '逆向工程工具': reverseEngine/basicDevtool.md 
      - '汇编语言': reverseEngine/assembly.md
  - 'Web Server':
    - '学习资源': server/trainingResource.md
    - 'http':
      - '安全认证方式': http/httpAuthenticate.md
      - 'URL': http/url.md
      - 'HTTP method': http/httpMethod.md
  - 'Docker':
    - '目录': docker/index.md
    - 'Dockerfile': docker/dockerfile.md
    
